name             'apache'
maintainer       'Niko Smeds'
maintainer_email 'nikosmeds@gmail.com'
license          'All Rights Reserved'
description      'Installs and configures apache web server'
version          '0.1.0'
